storage_backend: az

account:
    aws_account_id: 899133214451
    aws_lambda_role: pywren_exec_role_1
    aws_region: us-west-2

az:
    container: azure-webjobs-hosts
    pywren_prefix: pywren.jobs
    queue_name : pywrenqueue
    account_name: azure_storage_account_name
    access_key: azure_storage_access_key

runtime:
    runtime_storage: az
    az_name: foo 
    az_key:  bar
    az_container: azure-webjobs-hosts
    az_blob_name: pywren.runtime/pywren_runtime-2.7-default.tar.gz

